openapi: 3.0.0
info:
  title: "GraphWiki - comment service API"
  description: "GraphWiki - API definition for comment-service"
  version: "1.0.0"
servers:
  - url: http://localhost:8070/comment-service
    description: Local backend
  - url: http://localhost:9070/comment-service
    description: Remote backend

paths:
  /comment:
    $ref: "paths/byEntity.yaml"
  /comment/{id}:
    $ref: "paths/byId.yaml"


components:
  parameters:
    $ref: "params/urlParams.yaml"
  requestBodies:
    $ref: "params/requestBody.yaml"


  schemas:
    CommentTO:
      $ref: "definitions/comment/CommentTO.yaml"
    CreateCommentTO:
      $ref: "definitions/comment/CreateCommentTO.yaml"

    LinkTO:
      $ref: "definitions/LinkTO.yaml"


  securitySchemes:
    JWT:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Access token is required for specific resources
security:
  - JWT: []
